"""Add optional true values to datasets

Revision ID: daec26ec2fd8
Revises: 0cec8765aa73
Create Date: 2022-02-28 13:15:44.249098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daec26ec2fd8'
down_revision = '0cec8765aa73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('true_values', sa.LargeBinary(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'true_values')
    # ### end Alembic commands ###
