"""Added optional experiment to model_run; removed unique constraint

Revision ID: f8abf970e3cf
Revises: 
Create Date: 2022-02-26 12:25:31.630526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8abf970e3cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_run', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.drop_index('_dataset_name_uc', table_name='model_run')
    op.create_foreign_key(None, 'model_run', 'experiment', ['experiment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_run', type_='foreignkey')
    op.create_index('_dataset_name_uc', 'model_run', ['dataset_id', 'name'], unique=False)
    op.drop_column('model_run', 'experiment_id')
    # ### end Alembic commands ###
